notifications:
  email: false

language: node_js

node_js:
  - '8'

sudo: false

cache:
  directories:
    - '.eslintcache'
    - 'node_modules'

script:
  - npm run test

after_script:
  - npm i coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
